// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV3XI2wEIgcoZ3IVvvYP4cYR1tYMSes_k',
    appId: '1:657904558559:web:23e425e07c956d50a5a46a',
    messagingSenderId: '657904558559',
    projectId: 'flutterfirebasedemo-13810',
    authDomain: 'flutterfirebasedemo-13810.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-13810.firebasestorage.app',
    measurementId: 'G-95E0WNQNQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HsyNTsmk-DWSY224Vf8PM36SUln2rFQ',
    appId: '1:657904558559:android:7d5dc9b7efb8b86fa5a46a',
    messagingSenderId: '657904558559',
    projectId: 'flutterfirebasedemo-13810',
    storageBucket: 'flutterfirebasedemo-13810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNz4PQ0ZXHcRDCsJMPFfGU2yN_7-YYro',
    appId: '1:657904558559:ios:951078681b26b987a5a46a',
    messagingSenderId: '657904558559',
    projectId: 'flutterfirebasedemo-13810',
    storageBucket: 'flutterfirebasedemo-13810.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFNz4PQ0ZXHcRDCsJMPFfGU2yN_7-YYro',
    appId: '1:657904558559:ios:951078681b26b987a5a46a',
    messagingSenderId: '657904558559',
    projectId: 'flutterfirebasedemo-13810',
    storageBucket: 'flutterfirebasedemo-13810.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV3XI2wEIgcoZ3IVvvYP4cYR1tYMSes_k',
    appId: '1:657904558559:web:b9618ddd1f9c106aa5a46a',
    messagingSenderId: '657904558559',
    projectId: 'flutterfirebasedemo-13810',
    authDomain: 'flutterfirebasedemo-13810.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-13810.firebasestorage.app',
    measurementId: 'G-HJFFM3NZE6',
  );
}
